### ISSUE TITLE
  Creating plot object generates TypeError: module not callable

### ISSUE THREAD

**Issue by EricThomson** [kushalkolar/fastplotlib#72] opened 2022-12-16 14:36 UTC
Working with most recent update (updated few days ago, and I also just updated today):

```
from fastplotlib import Plot
plot = Plot()
```
Returns `TypeError: 'module' object is not callable`.

Other things are working fine (e.g., `ImageGraphic`).  I'm on Windows 10.

**Comment by EricThomson** [comment] 2022-12-16 18:37
```
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_18652/434463605.py in <module>
      1 from fastplotlib import Plot
----> 2 plot = Plot()

TypeError: 'module' object is not callable

```

**Comment by kushalkolar** [comment] 2022-12-17 00:24
I'm unable to reproduce this, it seems very bizarre. You sure this is the latest master branch? 

what if you do:

```python3
import fastplotlib
fastplotlib.__file__
```

**Comment by EricThomson** [comment] 2022-12-17 06:28
It's `None`. I tried installing a few ways:

The development install today (to try out the new api).

```
git clone https://github.com/kushalkolar/fastplotlib.git
cd fastplotlib
pip install -r requirements.txt
pip install -e 
```

The usual way:

`pip install git+https://github.com/kushalkolar/fastplotlib.git`

I'm getting the error with both.  I've never seen this before. Indeed it is bizarre.

**Comment by kushalkolar** [comment] 2022-12-17 06:32
`pip uninstall fastplotlib` before `pip install -e .` ?

**Comment by EricThomson** [comment] 2022-12-17 06:50
Yes, I tried that. 

But note this was all in a pretty old mesmerize virtual env with Python 3.8, so I just tried it with a fresh virtual env with python 3.9, and it seems to be working though with new errors based on the text stuff. With `from fastplotlib import Plot` I get:

```
FileNotFoundError                         Traceback (most recent call last)
Cell In[2], line 1
----> 1 from fastplotlib import Plot

File ~\development\dev_packages\fastplotlib\fastplotlib\__init__.py:1
----> 1 from .plot import Plot
      2 from .layouts import GridPlot
      3 from pathlib import Path

File ~\development\dev_packages\fastplotlib\fastplotlib\plot.py:2
      1 from typing import *
----> 2 import pygfx
      3 from wgpu.gui.auto import WgpuCanvas
      4 from .layouts._subplot import Subplot

File ~\miniconda3\envs\fpl\lib\site-packages\pygfx\__init__.py:7
      5 from .resources import *
      6 from .objects import *
----> 7 from .geometries import *
      8 from .materials import *
      9 from .cameras import *

File ~\miniconda3\envs\fpl\lib\site-packages\pygfx\geometries\__init__.py:16
      9 from ._polyhedron import (
     10     octahedron_geometry,
     11     icosahedron_geometry,
     12     dodecahedron_geometry,
     13     tetrahedron_geometry,
     14 )
     15 from ._toroidal import torus_knot_geometry, klein_bottle_geometry
---> 16 from ._text import TextGeometry, TextItem
     18 # Define __all__ for e.g. Sphinx
     19 __all__ = [
     20     ob.__name__
     21     for ob in globals().values()
     22     if (isinstance(ob, type) and issubclass(ob, Geometry))
     23     or (callable(ob) and ob.__name__.endswith("_geometry"))
     24 ]

File ~\miniconda3\envs\fpl\lib\site-packages\pygfx\geometries\_text.py:13
     11 from ._base import Geometry
     12 from ..resources import Buffer
---> 13 from ..utils import text as textmodule
     16 TEXT_ALIGN_ALTS = {
     17     "left": "start",
     18     "top": "start",
   (...)
     21     "bottom": "end",
     22 }
     23 ANCHOR_X_ALTS = {
     24     "left": "left",
     25     "center": "center",
     26     "middle": "center",
     27     "right": "right",
     28 }

File ~\miniconda3\envs\fpl\lib\site-packages\pygfx\utils\text\__init__.py:17
      1 """
      2 The six stages of text rendering (also see the README in this subpackage):
      3 
   (...)
     13 Rendering is implemented in the TextShader.
     14 """
     16 from ._fontfinder import FontFile  # noqa: F401
---> 17 from ._fontmanager import FontProps, FontManager, font_manager  # noqa: F401
     18 from ._atlas import glyph_atlas  # noqa: F401
     19 from ._tokenizers import tokenize_text, tokenize_markdown  # noqa: F401

File ~\miniconda3\envs\fpl\lib\site-packages\pygfx\utils\text\_fontmanager.py:363
    359         return msg
    362 # Instantiate the global/default font manager
--> 363 font_manager = FontManager()

File ~\miniconda3\envs\fpl\lib\site-packages\pygfx\utils\text\_fontmanager.py:126, in FontManager.__init__(self)
    124 self._warned_for_codepoints = set()
    125 self._family_to_font = {}  # name -> style -> FontFile
--> 126 self._load_default_font_index()
    127 self._load_fonts()

File ~\miniconda3\envs\fpl\lib\site-packages\pygfx\utils\text\_fontmanager.py:175, in FontManager._load_default_font_index(self)
    171 def _load_default_font_index(self):
    172 
    173     # Load the json
    174     index_filename = os.path.join(get_resources_dir(), "noto_default_index.json")
--> 175     with open(index_filename, "rt", encoding="utf-8") as f:
    176         ob = json.load(f)
    177     families, fnames, index = ob["families"], ob["filenames"], ob["index"]

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Eric\\miniconda3\\envs\\fpl\\lib\\site-packages\\pygfx\\pkg_resources\\noto_default_index.json'

```

**Comment by kushalkolar** [comment] 2022-12-17 07:10
I haven't merged the text PR into fastplotlib yet so this is something from pygfx.

Maybe:

`pip install freetype`

But I'm pretty sure freetype is in the setup.py for pygfx.

Are you able to run any of the basic pygfx examples? If not this seems like a pygfx issue.

**Comment by EricThomson** [comment] 2022-12-19 14:54
Yes this seems an issue with `pygfx`, even just importing `pygfx` throws the above error (this is in a new install/fresh environment).

**Comment by EricThomson** [comment] 2022-12-19 14:56
I'll see if I can reproduce with pure pygfx env and open issue there.

**Closed** 2022-12-19 17:03 UTC
